apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: admin-acks-policy
  namespace: openshift-config
spec:
  disabled: true
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: admin-ack-4.8-4.9-upgrade-ok
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              ack-4.8-kube-1.22-api-removals-in-4.9: "true"
            kind: ConfigMap
            metadata:
              name: admin-acks
              namespace: openshift-config
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-admin-acks-policy
  namespace: openshift-config
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-admin-acks-policy
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: admin-acks-policy
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
  name: placement-admin-acks-policy
  namespace: openshift-config
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
