apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-stable-4-8-upgrade
  namespace: openshift-config
spec:
  disabled: true
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: stable-4-8-upgrade-policy-update-service
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: ClusterVersion
            metadata:
              name: version
            spec:
              channel: stable-4.8
              upstream: https://sample-policy-engine-route-openshift-update-service.apps.shashank.nfvi.localdomain/api/upgrades_info/v1/graph
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: CatalogSource
            metadata:
              name: redhat-operator-index
              namespace: openshift-marketplace
            spec:
              image: registry.nec.nfvi.localdomain:5000/olm/olm-index-redhat-operator-index:v4.8
              sourceType: grpc

  remediationAction: enforce
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rule-stable-4-8-upgrade
  namespace: openshift-config
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-stable-4-8-upgrade
  namespace: openshift-config
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: rule-stable-4-8-upgrade
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: policy-stable-4-8-upgrade
