apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-stable-4-9-upgrade
  namespace: openshift-config
spec:
  disabled: true
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: stable-4-9-upgrade-policy-update-service
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: ClusterVersion
            metadata:
              name: version
            spec:
              channel: stable-4.9
              upstream: https://sample-policy-engine-route-openshift-update-service.apps.shashank.nfvi.localdomain/api/upgrades_info/v1/graph

  remediationAction: enforce
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rule-stable-4-9-upgrade
  namespace: openshift-config
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - nec1-nfvi-localdomain
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-stable-4-9-upgrade
  namespace: openshift-config
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: rule-stable-4-9-upgrade
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: policy-stable-4-9-upgrade
